# Generated by Django 2.2.24 on 2021-10-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_auto_20211031_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clases',
            new_name='Clase',
        ),
    ]
